version: '3.1'

services:
  telebot:
    image: '9b0f961a1807'
    container_name: telebot
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_URL=jdbc:postgresql://database:5432/postgres
    depends_on:
      - database
      - redis

  database:
    image: 'postgres'
    container_name: database
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: 'redis'
    container_name: "redis"
    ports:
      - "6379:6379"